<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Баннеры' => 'Banneri',
    'Контактные данные' => 'Date de contact',
    'О проекте' => 'Despre proiect',
    'E-mail не действительный!' => 'E-mail nu este validă !',
    'Email' => 'Email',
    'Главная' => 'Acasă',
    'Инфографика' => 'Infografică',
    'Молдова в ногу с Европой' => 'Moldova în pas cu Europa',
    'serg.ivanov@example.com (будет выслано письмо для подтверждения)' => '',
    'Аватар' => '',
    'Вверх' => 'Sus',
    'Запомнить меня' => '',
    'Запрашиваемая страница не существует!' => '',
    'Иванов' => '',
    'Имя' => '',
    'Неправильное имя пользователя или пароль' => '',
    'Нет такого пользователя' => '',
    'Пароль' => '',
    'Перейти в категорию' => 'Accesați categorie',
    'Повторите пароль' => '',
    'Поиск' => 'Căutare',
    'Полное имя' => '',
    'Смерить пароль' => '',
    'Создан' => '',
    'Сохранить' => '',
    'Справа внизу' => '',
    'Справа наверху' => '',
    'Справа посередине' => '',
    'Ссылка' => '',
    'Страницы не существует' => '',
    'Учетная запись не активна' => '',
    'Фамилия' => '',
    'ЧИТАТЬ ДАЛЕЕ' => 'MAI MULT',
    'Видеожурнал' => 'Videojurnal',
    'Фотоконкурс' => 'Fotoconcurs',
    'Социальные сети' => 'Socials',
    'События' => 'Eveniment',
    'Инфографика' => 'Infografica',
    'Фотоконкурс' => 'Concurs fotografic',
    'Календарь' => 'Calendar',
    'Будьте на связи'=>'Rămâneți conectat',
    'Контакты'=>'Contacte',
    'Тэги' => 'Tag-uri',
    'Название' => 'Titlu',
    'Видеожурнал' => 'Videojurnal',
    'Читайте также' => 'De asemenea citiți',
    'Близжайшие события' => 'Cele mai apropiate evenimente',
    'В той же рубрике' => 'În aceeași rubrică'
);
