<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"chartOptions.series" is expected to be an array.' => '',
  '"{attribute}" attribute must be defined' => '',
  '"{operation}" is an unsupported class operation.' => '',
  'Chart' => '',
  'Column summary configuration must be an array containing a "type" element.' => '',
  'Grid' => '',
  'Home' => '',
  'Not set' => '',
  'The "label" of a type must be defined.' => '',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '',
  'Unsupported column type. Supported column types are: "{types}"' => '',
  'You need to set the "series" attribute in order to render a chart' => '',
);
